[IL][HDX-10458] Registering SIGQUIT only if supported (#52)
What does this MR do?
-----------------------
SIGQUIT is a POSIX specific signal that is not supported by Windows.
Running the MCP server on Windows errors out because `signal` is missing
the `SIGQUIT` attribute on Windows. This PR fixes this bug by checking
if SIGQUIT is defined before registering the signal.

Does this MR meet the acceptance criteria?
--------------------------------------------

* [ ] Documentation created/updated
* [ ] Tests added for this feature/bug
* [ ] Does this change request have any security impacts?

Release Notes
---------------------------------------------------

* Major changes:
    *
* Minor changes:
    *
* Bugfixes:
    * Check if SIGQUIT is defined before registering hook
* Issues Closed:
    *
* Security impacts identified:
    *

Testing
--------------------------------------------
Run the MCP server on Windows and check that an error such as
`AttributeError: module 'signal' has no attribute 'SIGQUIT'` isn't
logged.